version: "3"
services:
  app:
    container_name: alist-strm
    image: 'jacksaoding/alist-strm:latest'
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /volume1/docker/alist-strm/config:/config
      - /volume1/docker/alist-strm/data:/data